"""
Synthetic Demo Data Generator for Paytm MerchantMind.

MANDATORY DISCLOSURE:
All data generated by this script is synthetic demo data.
It is created programmatically for hackathon demonstration purposes.
It does NOT represent or access real Paytm merchant or customer data.

Seeded Patterns (aligned with Blueprint Section 13):
1. Demo Merchant: Sharma General Store, Bengaluru (Kirana/Retail, 36 months old).
2. Customer Segmentation: 5 realistic segments:
   - VIP (~18): High spend, frequent, recent visits.
   - Loyal (~67): Consistent repeat purchasers.
   - New (~45): First visited in last 14 days, 1-2 transactions.
   - At-Risk (~43): Previously frequent, absent for 25-45 days.
   - Inactive (~126): Absent for 45+ days.
3. 90-day Transaction History (~2,500 transactions):
   - Weeks 1-10: Baseline steady volume.
   - Weeks 11-12: Recent decline (~16% drop overall, ~31% drop during 6-9 PM weekday evenings).
4. Realistic Expenses & Invoices:
   - Inventory (largest ~Rs 1,20,000/mo), Rent (Rs 35,000), Salary (Rs 45,000),
   - Electricity spike (+15% anomaly).
"""

import sys
import os
import json
import random
from datetime import datetime, date, timedelta, timezone
from decimal import Decimal
from typing import Dict, List, Any, Optional
import numpy as np

# Ensure backend root is on sys.path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
if BACKEND_ROOT not in sys.path:
    sys.path.insert(0, BACKEND_ROOT)


def set_seed(seed: int = 42) -> None:
    """Set random seed for deterministic reproducibility."""
    random.seed(seed)
    np.random.seed(seed)


def generate_merchant_data(merchant_id: str = "demo-merchant-001") -> Dict[str, Any]:
    """Generate profile for the primary demo merchant."""
    return {
        "merchant_id": merchant_id,
        "business_name": "Sharma General Store",
        "business_type": "Kirana & Grocery",
        "location": "Indiranagar, Bengaluru, Karnataka",
        "business_age": 36,
        "created_at": (datetime.now(timezone.utc) - timedelta(days=36 * 30)).isoformat()
    }


def generate_customers_data(
    merchant_id: str = "demo-merchant-001",
    now: Optional[datetime] = None
) -> List[Dict[str, Any]]:
    """Generate realistic customer cohort with the 5 specific segments."""
    if now is None:
        now = datetime.now(timezone.utc)

    customers = []

    first_names = [
        "Aarav", "Aditi", "Amit", "Ananya", "Arjun", "Bhavna", "Chetan", "Deepa",
        "Divya", "Gaurav", "Harish", "Ishaan", "Kavita", "Manish", "Meera", "Neha",
        "Nikhil", "Pooja", "Pranav", "Priya", "Rahul", "Rajesh", "Ritu", "Rohan",
        "Rohit", "Sachin", "Sandhya", "Sanjay", "Shreya", "Sneha", "Suresh", "Swati",
        "Tanvi", "Varun", "Vikas", "Vinay", "Vivek"
    ]
    last_names = [
        "Sharma", "Verma", "Patel", "Reddy", "Rao", "Nair", "Iyer", "Gupta",
        "Kulkarni", "Deshmukh", "Joshi", "Bhat", "Mehta", "Singh", "Kumar", "Das"
    ]

    # Target segment counts per blueprint: VIP 18, Loyal 67, New 45, At-Risk 43, Inactive 126
    segment_specs = [
        ("VIP", 18, (1, 5), (15, 30), (12000, 25000)),
        ("Loyal", 67, (2, 10), (8, 18), (5000, 11000)),
        ("New", 45, (1, 14), (1, 2), (300, 1500)),
        ("At-Risk", 43, (25, 45), (6, 14), (3500, 8000)),
        ("Inactive", 126, (46, 90), (4, 12), (2000, 6000)),
    ]

    cust_num = 1
    for seg_name, count, recency_range, txn_range, spend_range in segment_specs:
        for _ in range(count):
            c_id = f"cust-{merchant_id[-3:]}-{cust_num:04d}"
            name = f"{random.choice(first_names)} {random.choice(last_names)}"
            phone = f"+91 98{random.randint(10000000, 99999999)}"
            txns = random.randint(*txn_range)
            spend = Decimal(str(round(random.uniform(*spend_range), 2)))
            avg_spend = Decimal(str(round(float(spend) / max(txns, 1), 2)))

            days_ago = random.randint(*recency_range)
            last_tx_time = now - timedelta(days=days_ago, hours=random.randint(1, 12))

            customers.append({
                "customer_id": c_id,
                "merchant_id": merchant_id,
                "name": name,
                "phone": phone,
                "transaction_count": txns,
                "total_spend": float(spend),
                "average_transaction": float(avg_spend),
                "last_transaction": last_tx_time.isoformat(),
                "segment": seg_name,
                "created_at": (now - timedelta(days=random.randint(90, 365))).isoformat()
            })
            cust_num += 1

    return customers


def generate_transactions_data(
    merchant_id: str,
    customers: List[Dict[str, Any]],
    now: Optional[datetime] = None
) -> List[Dict[str, Any]]:
    """
    Generate 90 days of transactions with realistic retail patterns:
    - Normal baseline weeks 1-10 (~28-35 txns/day)
    - Weekday evening decline during weeks 11-12 (~31% drop 6-9 PM)
    """
    if now is None:
        now = datetime.now(timezone.utc)

    transactions = []
    payment_methods = ["UPI", "UPI", "UPI", "UPI", "Card", "Cash"]

    # Map customers by ID
    customer_ids = [c["customer_id"] for c in customers]
    tx_counter = 1

    for day_offset in range(89, -1, -1):
        target_date = (now - timedelta(days=day_offset)).date()
        is_recent_decline_period = (day_offset <= 14)  # Weeks 11-12
        is_weekend = target_date.weekday() in (5, 6)

        # Base daily transaction count
        if is_weekend:
            daily_txns = random.randint(34, 45)
        else:
            daily_txns = random.randint(26, 36)

        # Generate timestamps throughout store operating hours (8 AM - 10 PM)
        for _ in range(daily_txns):
            # Hour probability distribution
            hour_roll = random.random()
            if hour_roll < 0.25:
                # Morning 8-12
                hour = random.randint(8, 11)
            elif hour_roll < 0.50:
                # Afternoon 12-5
                hour = random.randint(12, 16)
            elif hour_roll < 0.90:
                # Evening 6-9 PM (Drop period!)
                if is_recent_decline_period and not is_weekend and random.random() < 0.35:
                    # Drop 35% of weekday evening transactions to model the 31% drop!
                    continue
                hour = random.randint(18, 20)
            else:
                # Night 9-10 PM
                hour = random.randint(21, 22)

            minute = random.randint(0, 59)
            second = random.randint(0, 59)
            tx_time = datetime(
                target_date.year, target_date.month, target_date.day,
                hour, minute, second, tzinfo=timezone.utc
            )

            # Amount logic: Groceries range from Rs 40 to Rs 3,500
            amount_weight = random.random()
            if amount_weight < 0.60:
                amount = round(random.uniform(50.0, 350.0), 2)
            elif amount_weight < 0.90:
                amount = round(random.uniform(350.0, 1200.0), 2)
            else:
                amount = round(random.uniform(1200.0, 3200.0), 2)

            cust_id = random.choice(customer_ids) if random.random() < 0.85 else None
            status = "success" if random.random() > 0.02 else "failed"

            transactions.append({
                "transaction_id": f"tx-{merchant_id[-3:]}-{tx_counter:06d}",
                "merchant_id": merchant_id,
                "customer_id": cust_id,
                "timestamp": tx_time.isoformat(),
                "amount": float(amount),
                "payment_method": random.choice(payment_methods),
                "status": status
            })
            tx_counter += 1

    return transactions


def generate_expenses_data(
    merchant_id: str,
    now: Optional[datetime] = None
) -> List[Dict[str, Any]]:
    """Generate 3 months of operational expenses with an electricity spike anomaly."""
    if now is None:
        now = datetime.now(timezone.utc)

    expenses = []
    exp_counter = 1

    for month_back in range(2, -1, -1):
        month_date = now - timedelta(days=month_back * 30)

        # Inventory batches (weekly)
        for week in range(4):
            exp_date = (month_date - timedelta(days=21 - week * 7)).date()
            expenses.append({
                "expense_id": f"exp-{merchant_id[-3:]}-{exp_counter:04d}",
                "merchant_id": merchant_id,
                "date": exp_date.isoformat(),
                "category": "Inventory",
                "amount": float(round(random.uniform(28000.0, 32000.0), 2)),
                "vendor": "Metro Cash & Carry / Bangalore FMCG Dist.",
                "notes": f"Weekly FMCG restocking batch {week + 1}"
            })
            exp_counter += 1

        # Rent (monthly on 1st)
        rent_date = date(month_date.year, month_date.month, 1)
        expenses.append({
            "expense_id": f"exp-{merchant_id[-3:]}-{exp_counter:04d}",
            "merchant_id": merchant_id,
            "date": rent_date.isoformat(),
            "category": "Rent",
            "amount": 35000.00,
            "vendor": "Commercial Property Landlord",
            "notes": "Storefront premises monthly lease"
        })
        exp_counter += 1

        # Staff salaries (monthly on 5th)
        salary_date = date(month_date.year, month_date.month, 5)
        expenses.append({
            "expense_id": f"exp-{merchant_id[-3:]}-{exp_counter:04d}",
            "merchant_id": merchant_id,
            "date": salary_date.isoformat(),
            "category": "Salaries",
            "amount": 45000.00,
            "vendor": "Store Helpers & Cashier (2 staff)",
            "notes": "Monthly payroll"
        })
        exp_counter += 1

        # Electricity bill (spike in current month: +15%)
        elec_date = date(month_date.year, month_date.month, 12)
        elec_amount = 17850.00 if month_back == 0 else 15500.00
        expenses.append({
            "expense_id": f"exp-{merchant_id[-3:]}-{exp_counter:04d}",
            "merchant_id": merchant_id,
            "date": elec_date.isoformat(),
            "category": "Utilities",
            "amount": elec_amount,
            "vendor": "BESCOM (Bangalore Electricity)",
            "notes": "Store refrigeration & air conditioning electricity bill"
        })
        exp_counter += 1

        # Miscellaneous / Packaging
        misc_date = date(month_date.year, month_date.month, 18)
        expenses.append({
            "expense_id": f"exp-{merchant_id[-3:]}-{exp_counter:04d}",
            "merchant_id": merchant_id,
            "date": misc_date.isoformat(),
            "category": "Packaging & Misc",
            "amount": float(round(random.uniform(4000.0, 6000.0), 2)),
            "vendor": "Krishna Packaging Supplies",
            "notes": "Carry bags, thermal billing rolls, sanitization"
        })
        exp_counter += 1

    return expenses


def generate_invoices_data(
    merchant_id: str,
    now: Optional[datetime] = None
) -> List[Dict[str, Any]]:
    """Generate vendor supplier invoices."""
    if now is None:
        now = datetime.now(timezone.utc)

    invoices = []
    inv_counter = 1

    vendors = [
        ("Metro Cash & Carry", 32500.00, "paid"),
        ("Hindustan Unilever Dist.", 18400.00, "paid"),
        ("ITC Agri-Business Hub", 14200.00, "paid"),
        ("Amul Dairy Supply", 9800.00, "pending"),
        ("Britannia Direct Wholesale", 7600.00, "pending"),
        ("Tata Consumer Products", 12300.00, "paid"),
    ]

    for vendor, amount, status in vendors:
        inv_date = (now - timedelta(days=random.randint(5, 45))).date()
        due_date = inv_date + timedelta(days=15)
        invoices.append({
            "invoice_id": f"inv-{merchant_id[-3:]}-{inv_counter:04d}",
            "merchant_id": merchant_id,
            "vendor": vendor,
            "amount": float(amount),
            "date": inv_date.isoformat(),
            "due_date": due_date.isoformat(),
            "status": status
        })
        inv_counter += 1

    return invoices


def generate_campaigns_data(merchant_id: str) -> List[Dict[str, Any]]:
    """Generate historical and template promotional campaigns."""
    now = datetime.now(timezone.utc)
    return [
        {
            "campaign_id": f"camp-{merchant_id[-3:]}-001",
            "merchant_id": merchant_id,
            "target_segment": "Inactive",
            "offer_type": "cashback",
            "offer_value": 50.00,
            "min_transaction": 299.00,
            "start_date": (now - timedelta(days=60)).isoformat(),
            "end_date": (now - timedelta(days=45)).isoformat(),
            "status": "completed",
            "estimated_cost": 2500.00,
            "actual_revenue": 14200.00,
            "actual_txn_count": 38,
            "created_at": (now - timedelta(days=65)).isoformat()
        },
        {
            "campaign_id": f"camp-{merchant_id[-3:]}-002",
            "merchant_id": merchant_id,
            "target_segment": "At-Risk",
            "offer_type": "discount",
            "offer_value": 10.00,
            "min_transaction": 499.00,
            "start_date": (now - timedelta(days=30)).isoformat(),
            "end_date": (now - timedelta(days=15)).isoformat(),
            "status": "completed",
            "estimated_cost": 3000.00,
            "actual_revenue": 19500.00,
            "actual_txn_count": 29,
            "created_at": (now - timedelta(days=35)).isoformat()
        },
        {
            "campaign_id": f"camp-{merchant_id[-3:]}-003",
            "merchant_id": merchant_id,
            "target_segment": "At-Risk",
            "offer_type": "cashback",
            "offer_value": 75.00,
            "min_transaction": 399.00,
            "start_date": None,
            "end_date": None,
            "status": "pending",
            "estimated_cost": 3225.00,
            "actual_revenue": 0.00,
            "actual_txn_count": 0,
            "created_at": now.isoformat()
        }
    ]


def generate_full_synthetic_dataset(
    merchant_id: str = "demo-merchant-001",
    seed: int = 42
) -> Dict[str, Any]:
    """Generate complete bundle of synthetic entities with seeded business patterns."""
    set_seed(seed)
    now = datetime.now(timezone.utc)

    merchant = generate_merchant_data(merchant_id)
    customers = generate_customers_data(merchant_id, now)
    transactions = generate_transactions_data(merchant_id, customers, now)
    expenses = generate_expenses_data(merchant_id, now)
    invoices = generate_invoices_data(merchant_id, now)
    campaigns = generate_campaigns_data(merchant_id)

    return {
        "metadata": {
            "disclosure": (
                "ALL DATA IS SYNTHETIC DEMO DATA PROGRAMMATICALLY GENERATED FOR DEMONSTRATION PURPOSES. "
                "DOES NOT ACCESS OR CONTAIN REAL PAYTM DATA."
            ),
            "generated_at": now.isoformat(),
            "random_seed": seed,
            "merchant_id": merchant_id,
            "counts": {
                "merchants": 1,
                "customers": len(customers),
                "transactions": len(transactions),
                "expenses": len(expenses),
                "invoices": len(invoices),
                "campaigns": len(campaigns)
            }
        },
        "merchant": merchant,
        "customers": customers,
        "transactions": transactions,
        "expenses": expenses,
        "invoices": invoices,
        "campaigns": campaigns
    }


def save_dataset_to_json(dataset: Dict[str, Any], output_dir: Optional[str] = None) -> None:
    """Save synthetic dataset to JSON fallback files in backend/data/fallback/."""
    if output_dir is None:
        output_dir = os.path.join(BACKEND_ROOT, "data", "fallback")
    os.makedirs(output_dir, exist_ok=True)

    # Save full dataset
    full_path = os.path.join(output_dir, "synthetic_dataset_full.json")
    with open(full_path, "w", encoding="utf-8") as f:
        json.dump(dataset, f, indent=2)

    # Save individual entities for modular fallback consumption
    for key in ["merchant", "customers", "transactions", "expenses", "invoices", "campaigns"]:
        sub_path = os.path.join(output_dir, f"{key}.json")
        with open(sub_path, "w", encoding="utf-8") as f:
            json.dump(dataset[key], f, indent=2)

    print(f"[OK] Synthetic dataset successfully written to: {output_dir}")


def seed_database_from_dataset(dataset: Dict[str, Any]) -> bool:
    """Insert synthetic data into database via SQLAlchemy models."""
    from app.core.database import SessionLocal, init_db
    from app.models import Merchant, Customer, Transaction, Expense, Invoice, Campaign

    # Ensure tables exist
    init_db()

    session = SessionLocal()
    try:
        # Check if merchant already exists
        m_data = dataset["merchant"]
        existing = session.get(Merchant, m_data["merchant_id"])
        if existing:
            print(f"Merchant '{m_data['merchant_id']}' already seeded. Skipping DB insertion.")
            return True

        # Insert Merchant
        merchant = Merchant(
            merchant_id=m_data["merchant_id"],
            business_name=m_data["business_name"],
            business_type=m_data["business_type"],
            location=m_data["location"],
            business_age=m_data["business_age"],
            created_at=datetime.fromisoformat(m_data["created_at"])
        )
        session.add(merchant)
        session.flush()

        # Insert Customers
        for c in dataset["customers"]:
            customer = Customer(
                customer_id=c["customer_id"],
                merchant_id=c["merchant_id"],
                name=c["name"],
                phone=c["phone"],
                transaction_count=c["transaction_count"],
                total_spend=Decimal(str(c["total_spend"])),
                average_transaction=Decimal(str(c["average_transaction"])),
                last_transaction=datetime.fromisoformat(c["last_transaction"]) if c["last_transaction"] else None,
                segment=c["segment"],
                created_at=datetime.fromisoformat(c["created_at"])
            )
            session.add(customer)

        # Insert Transactions
        for t in dataset["transactions"]:
            transaction = Transaction(
                transaction_id=t["transaction_id"],
                merchant_id=t["merchant_id"],
                customer_id=t["customer_id"],
                timestamp=datetime.fromisoformat(t["timestamp"]),
                amount=Decimal(str(t["amount"])),
                payment_method=t["payment_method"],
                status=t["status"]
            )
            session.add(transaction)

        # Insert Expenses
        for e in dataset["expenses"]:
            expense = Expense(
                expense_id=e["expense_id"],
                merchant_id=e["merchant_id"],
                date=date.fromisoformat(e["date"]),
                category=e["category"],
                amount=Decimal(str(e["amount"])),
                vendor=e["vendor"],
                notes=e.get("notes")
            )
            session.add(expense)

        # Insert Invoices
        for inv in dataset["invoices"]:
            invoice = Invoice(
                invoice_id=inv["invoice_id"],
                merchant_id=inv["merchant_id"],
                vendor=inv["vendor"],
                amount=Decimal(str(inv["amount"])),
                date=date.fromisoformat(inv["date"]),
                due_date=date.fromisoformat(inv["due_date"]) if inv.get("due_date") else None,
                status=inv["status"]
            )
            session.add(invoice)

        # Insert Campaigns
        for camp in dataset["campaigns"]:
            campaign = Campaign(
                campaign_id=camp["campaign_id"],
                merchant_id=camp["merchant_id"],
                target_segment=camp["target_segment"],
                offer_type=camp["offer_type"],
                offer_value=Decimal(str(camp["offer_value"])),
                min_transaction=Decimal(str(camp["min_transaction"])),
                start_date=datetime.fromisoformat(camp["start_date"]) if camp.get("start_date") else None,
                end_date=datetime.fromisoformat(camp["end_date"]) if camp.get("end_date") else None,
                status=camp["status"],
                estimated_cost=Decimal(str(camp["estimated_cost"])),
                actual_revenue=Decimal(str(camp["actual_revenue"])),
                actual_txn_count=camp["actual_txn_count"],
                created_at=datetime.fromisoformat(camp["created_at"])
            )
            session.add(campaign)

        session.commit()
        print(f"[OK] Database successfully seeded for merchant '{m_data['merchant_id']}'")
        return True
    except Exception as exc:
        session.rollback()
        print(f"[ERROR] Failed to seed database: {exc}")
        return False
    finally:
        session.close()


def main():
    """CLI runner for synthetic data generator."""
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass

    print("=" * 70)
    print("Paytm MerchantMind - Synthetic Data Generator")
    print("MANDATORY NOTICE: ALL DATA IS SYNTHETIC (DEMO PURPOSES ONLY)")
    print("=" * 70)

    dataset = generate_full_synthetic_dataset()
    meta = dataset["metadata"]["counts"]
    print(f"Generated:")
    print(f"  - Merchants:    {meta['merchants']}")
    print(f"  - Customers:    {meta['customers']}")
    print(f"  - Transactions: {meta['transactions']}")
    print(f"  - Expenses:     {meta['expenses']}")
    print(f"  - Invoices:     {meta['invoices']}")
    print(f"  - Campaigns:    {meta['campaigns']}")

    # Save to JSON fallback
    save_dataset_to_json(dataset)

    # If --db flag provided, attempt database seeding
    if "--db" in sys.argv or "--seed-db" in sys.argv:
        print("\nAttempting database seeding...")
        seed_database_from_dataset(dataset)

    print("=" * 70)


if __name__ == "__main__":
    main()
